platform :ios, '6.0' 

link_with ['Example', 'ExampleTests']


pod "SHObjectUserInfo"
pod "SHSegueBlocks"
pod "SHTestCaseAdditions", :git => "https://github.com/seivan/SHTestCaseAdditions"
pod 'SHKeyValueObserverBlocks', :path => '../'

